#!/bin/bash

# Push changes to two remotes at once
# It allows pass extra parameters to both push commands. As instance: git push2 -f

source "helpers.sh"

h1 "Pushing to both remotes"

exec "git push $1 $origin_remote"
exec "git push $1 $fork_remote"

h2 "Done!"
