#!/bin/bash

# Opens a interactive rebase of all branch commits

source "helpers.sh"

branch="$(current_branch)"

base_branch=$1
if [ -z $1 ]
then
  base_branch="main"
fi

h1 "Squashing commits from $branch since $base_branch"

sha_id="$(git merge-base $branch $base_branch)"
exec "git rebase -i $sha_id"

h2 "Done!"
