#!/bin/bash

# Pulls master from original repo, pushes last changes to the fork repo,
# rebases current work to the new master and pushes it to both remotes
# Change base branch passing it as an argument

source helpers.sh

# Get current branch
branch="$(current_branch)"

base_branch=$1
if [ -z $1 ]
then
  base_branch="main"
fi

if [ "$branch" = "master"  ]
then
  h1 "Branch is master. Aborting"
  exit
fi

if [ "$branch" = "main"  ]
then
  h1 "Branch is main. Aborting"
  exit
fi

h1 "Syncing $branch on top of $base_branch"

h2 "(1/2) Updating $base_branch..."
exec "git checkout $base_branch"
exec "git pull $origin_remote"

#Rebase branch to main and force push it
h2 "(2/2) Rebasing current branch..."
exec "git checkout $branch"
exec "git rebase $base_branch"
exec "git push $origin_remote"

h2 "Done!"
