#!/bin/bash

# Pulls master from original repo, syncs it up to the folk, and rebases current work to the new master

source githelpers.sh

# Get current branch
branch="$(git branch | grep \* | cut -d ' ' -f2)"
h1 "Sync $branch"

# Update master and push to fork
h2 "(1/2) Updating master..."
exec "git checkout master"
exec "git pull $spin_remote"
exec "git push $origin_remote"

#Rebase branch to master and force push it to both remotes
h2 "(2/2) Rebasing current branch..."
exec "git checkout $branch"
exec "git rebase master"
exec "git push -f $marsbased_remote"
exec "git push -f $origin_remote"

h2 "Done!"
