#!/bin/bash

# Push changes to two remotes at once

#Conf
origin_remote="origin"
fork_remote="mb"
# End conf

source "githelpers.sh"

h1 "Pushing to both remotes"

git push $origin_remote
git push $fork_remote

h2 "Done!"
